#
# Group_vars: OSEv3
#
---
ansible_ssh_user: 'root'
ansible_user: 'root'
ansible_become: 'yes'
openshift_master_api_port: '443'
openshift_master_console_port: '443'
openshift_deployment_type: 'origin'
#openshift_is_atomic: false
os_firewall_use_firewalld: true
# openshift_node_proxy_mode: 'userspace'
# OKD Additional repos in case not released yet to centos
openshift_additional_repos:
  - id: 'centos-okd-ci'
    name: 'centos-okd-ci'
    baseurl: 'https://rpms.svc.ci.openshift.org/openshift-origin-v3.11'
    gpgcheck: '0'
    enabled: '1'

openshift_enable_service_catalog: false
# Registry tags
# https://hub.docker.com/r/ansibleplaybookbundle/origin-ansible-service-broker/tags
ansible_service_broker_install: false
ansible_service_broker_registry_tag: '7d5015c'
template_service_broker_install: false
openshift_master_default_subdomain: 'apps.baloise.dev'
openshift_master_cluster_hostname: 'api-lb.okd.baloise.dev'
openshift_master_cluster_public_hostname: 'console.baloise.dev'
openshift_override_hostname_check: 'true'
openshift_master_identity_providers:
  - name: 'github'
    login: 'true'
    challenge: 'false'
    kind: 'GitHubIdentityProvider'
    clientID: "{{ github_client_id }}"
    clientSecret: "{{ github_client_secret }}" 
    organizations:
      - baloise-incubator
osm_cluster_network_cidr: '10.30.0.0/16'
openshift_portal_net: '172.30.0.0/16'
osm_host_subnet_length: '8'
openshift_disable_check: 'disk_availability,memory_availability,docker_storage,package_availability,package_version,docker_image_availability'
openshift_hosted_manage_router: 'true'
openshift_hosted_router_selector: 'node-role.kubernetes.io/infra=true'
openshift_hosted_manage_registry: 'true'
openshift_registry_selector: 'node-role.kubernetes.io/infra=true'
openshift_hosted_registry_replicas: '1'
openshift_hosted_registry_routehost: 'registry.apps.baloise.dev'
openshift_hosted_registry_routetermination: 'reencrypt'

openshift_hosted_registry_routecertificates:
  certfile: '/etc/pki/tls/certs/domains-fullchain.pem'
  keyfile: '/etc/pki/tls/private/domains-key.pem'
  cafile: '/etc/pki/tls/certs/le-ca.cer'

# Cert
openshift_master_overwrite_named_certificates: 'true'
openshift_certificate_expiry_warning_days: '0'
openshift_master_named_certificates:
  - certfile: '/etc/pki/tls/certs/domains-fullchain.pem'
    keyfile: '/etc/pki/tls/private/domains-key.pem'
    cafile: '/etc/pki/tls/certs/le-ca.cer'
    names:
      - 'console.baloise.dev'
openshift_hosted_router_certificate:
  certfile: '/etc/pki/tls/certs/domains-fullchain.pem'
  keyfile: '/etc/pki/tls/private/domains-key.pem'
  cafile: '/etc/pki/tls/certs/le-ca.cer' 

# Monitoring
openshift_cluster_monitoring_operator_install: true
openshift_cluster_monitoring_operator_node_selector:
  node-role.kubernetes.io/master: 'true'

# EFK Logging
openshift_logging_install_logging: 'false'
openshift_logging_kibana_hostname: 'logging.apps.baloise.dev'
openshift_logging_use_ops: 'false'
openshift_logging_master_url: 'https://kubernetes.default.svc.cluster.local'
openshift_logging_public_master_url: 'console.baloise.dev'
openshift_logging_curator_default_days: '14'
openshift_logging_es_memory_limit: '2Gi'
openshift_logging_es_cpu_limit: '1'
openshift_logging_es_pvc_dynamic: 'true'
openshift_logging_es_pvc_size: '30Gi'
openshift_logging_curator_nodeselector:
  node-role.kubernetes.io/infra: 'true'
openshift_logging_es_nodeselector:
  node-role.kubernetes.io/compute: 'true'
openshift_logging_fluentd_nodeselector:
  fluentd: 'true'
openshift_logging_kibana_nodeselector:
  node-role.kubernetes.io/infra: 'true'

# Metrics
openshift_metrics_install_metrics: 'true'
openshift_metrics_hawkular_hostname: 'metrics.apps.baloise.dev'
openshift_metrics_cassandra_requests_memory: '2Gi'
openshift_metrics_cassandra_limits_memory: '2Gi'
openshift_metrics_cassandra_requests_cpu: '500m'
openshift_metrics_cassandra_limits_cpu: '1'
openshift_metrics_hawkular_replicas: '1'
openshift_metrics_hawkular_requests_memory: '1.5Gi'
openshift_metrics_hawkular_limits_memory: '1.5Gi'
openshift_metrics_hawkular_requests_cpu: '100m'
openshift_metrics_hawkular_limits_cpu: '1'
openshift_metrics_duration: '14'
openshift_metrics_cassandra_storage_type: 'dynamic'
openshift_metrics_cassandra_storage_class_name: 'rook-ceph-block'
openshift_metrics_cassandra_pvc_size: '10Gi'
openshift_metrics_cassandra_nodeselector:
  node-role.kubernetes.io/infra: 'true'
openshift_metrics_hawkular_nodeselector:
  node-role.kubernetes.io/infra: 'true'
openshift_metrics_heapster_nodeselector:
  node-role.kubernetes.io/infra: 'true'
openshift_metrics_heapster_requests_memory: '128Mi'
openshift_metrics_heapster_limits_memory: '128Mi'

# Metrics Server
openshift_metrics_server_install: true
openshift_metrics_server_node_selector:
  node-role.kubernetes.io/infra: 'true'

# Enable OLM 
openshift_enable_olm: false

openshift_template_service_broker_namespaces:
  - 'openshift'

openshift_master_admission_plugin_config:
  openshift.io/ImagePolicy:
    configuration:
      apiVersion: v1
      executionRules:
        - matchImageAnnotations:
            - key: images.openshift.io/deny-execution
              value: 'true'
          name: execution-denied
          onResources:
            - resource: pods
            - resource: builds
          reject: true
          skipOnResolutionFailure: true
      kind: ImagePolicyConfig
  EventRateLimit:
    configuration:
      apiVersion: eventratelimit.admission.k8s.io/v1alpha1
      disable: true
      kind: Configuration
      limits:
        - type: User
          qps: 500
          burst: 500
        - type: Namespace
          qps: 500
          burst: 5000
        - type: Server
          qps: 500
          burst: 2000
  PersistentVolumeClaimResize:
    configuration:
      apiVersion: v1
      kind: DefaultAdmissionConfig
      disable: true

openshift_node_groups_edits: &groupEdits
  - key: kubeletArguments.feature-gates
    value:
      - RotateKubeletClientCertificate=true,RotateKubeletServerCertificate=true,SupportPodPidsLimit=true,MountPropagation=true
  - key: kubeletArguments.pod-max-pids
    value:
      - '1000'
  - key: kubeletArguments.anonymous-auth
    value:
      - 'false'
  - key: kubeletArguments.protect-kernel-defaults
    value:
      - 'true'
  - key: kubeletArguments.streaming-connection-idle-timeout
    value:
      - 5m
  - key: kubeletArguments.make-iptables-util-chains
    value:
      - 'true'
#  - key: kubeletArguments.event-qps
#    value:
#      - '0'
  - key: kubeletArguments.volume-plugin-dir
    value:
      - '/etc/kubernetes/kubelet-plugins/volume/exec'
  - key: servingInfo.cipherSuites
    value:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      - TLS_RSA_WITH_AES_128_GCM_SHA256
      - TLS_RSA_WITH_AES_256_GCM_SHA384
      - TLS_RSA_WITH_AES_256_CBC_SHA

openshift_node_groups:
  - name: node-config-master
    labels:
      - 'node-role.kubernetes.io/master=true'
    edits: *groupEdits

  - name: node-config-compute
    labels:
      - 'node-role.kubernetes.io/compute=true'
    edits: *groupEdits

  - name: node-config-compute-infra
    labels:
      - 'node-role.kubernetes.io/infra=true'
      - 'node-role.kubernetes.io/compute=true'
    edits: *groupEdits

